"""add professional_id to services

Revision ID: a3881cb4fbaa
Revises: 59fddfc47fc8
Create Date: 2026-03-28 15:01:37.332296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3881cb4fbaa'
down_revision: Union[str, Sequence[str], None] = '59fddfc47fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('professional_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'users', ['professional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'professional_id')
    # ### end Alembic commands ###
